### ISSUE TITLE
Memory usage about 12G,it is normal?

### ISSUE THREAD

**Issue by rc452860** [rohitghatol/spring-boot-microservices#16]
I use Vmware test this project,and system is ubunut 17.04,allocate 8G ram,run this project a later that system be stuck. any operation is invaild.

**Comment by rc452860** [comment]
when i put this project in tencent cloud with 16G ram，I use `top` to see the java process ram usage about 12G.the project can be start normal.

**Comment by anilallewar** [comment]
if you are running all projects then it might take up memory, I can run them on Mac with 16 GB RAM without any issues. I would suggest you use the -Xmx flag to limit the memory to 1 GB for all the servers when you start them.

**Comment by rc452860** [comment]
I know that ,but I just don't know that the other guys have seem problem。I was slove the problem,however，thanks your reply
